version: "2"
linters:
  enable:
    - bodyclose
    - copyloopvar
    - errorlint
    - gosec
    - makezero
    - paralleltest
    - perfsprint
    - revive
    - unconvert
    - unparam
    - wastedassign
  settings:
    gosec:
      config:
        G306: "0666"
  exclusions:
    paths:
      - _test
    rules:
      - linters:
          - revive
        text: 'package-comments: should have a package comment'

      - linters:
          - staticcheck
        # Ignoring "could remove embedded field <FIELD> from selector"
        # Stick to current behavior and being explicit of the method to call of the embedded struct.
        text: 'QF1008:'

issues:
  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 0

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/fraenky8/tables-to-go/v2
  exclusions:
    paths:
      - _test
