// Code generated by tables-to-go. DO NOT EDIT.
// versions:
// 	tables-to-go v0.0.0-test
// source: user

package dto

import (
	"database/sql"
)

type User struct {
	ID         int            `db:"id"`
	UserID     int            `db:"user_id"`
	Email      string         `db:"email"`
	WebsiteURL sql.NullString `db:"website_url"`
}
