name: Go & Lint
on: [push]
permissions:
  contents: read
jobs:
  golangci:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  build:
    name: Build & Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build tables-to-go
        run: go build -v -mod=vendor .

      - name: Run unit tests
        run: go test -v -mod=vendor -race ./...

      - name: Run integration tests
        # Run integration tests only on ubuntu-latest.
        #
        # Because there is no docker installed on MacOS, see here
        # https://github.community/t5/GitHub-Actions/Why-is-Docker-not-installed-on-macOS/td-p/39364
        #
        # And on Windows we get this error:
        #
        # vendor\github.com\ory\dockertest\docker\pkg\system\filesys_windows.go:113:24:
        #  cannot use uintptr(unsafe.Pointer(&sd[0])) (type uintptr) as type *"golang.org/x/sys/windows".SECURITY_DESCRIPTOR in assignment
        #
        if: matrix.platform == 'ubuntu-latest'
        run: go test -v -mod=vendor -tags=integration ./test/...
